In [14]:
%load_ext autoreload
%autoreload 2

In [15]:
# make models iside src importable here. For uv this does not matter,
# or when using .venv, but does matter when using global
from util import make_dir_modules_importable
make_dir_modules_importable()

Adding: D:\Documents\Ciencias de datos\Ciencia de datos 2\PRACTICAS\uasd-ds-2\unidad01\LAB02\src to sys.path

In [17]:
# fetch data
from lab02.data import fetch_bank_note_data_from_file
backnote_auth_df = fetch_bank_note_data_from_file()

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Documents\\Ciencias de datos\\Ciencia de datos 2\\PRACTICAS\\uasd-ds-2\\unidad01\\data\\data_banknote_authentication.txt'

In [94]:
import pandas as pd

feature_columns = list(backnote_auth.x.columns)
target_columns = list(backnote_auth.y.columns)

print("Audit of the data as it comes from repo: https://archive.ics.uci.edu/dataset/267/banknote+authentication ")
print(f"  - Feature columns: {feature_columns}")
print(f"  - Target columns: {target_columns}")
print("  - Feature: ", backnote_auth.x.shape)
print("  - Target: ", backnote_auth.y.shape)

audit = pd.DataFrame({
    "tipo": backnote_auth.x.dtypes.astype(str),
    "ausentes": backnote_auth.x.isna().sum(),
    "porcentaje_ausentes": (backnote_auth.x.isna().mean()*100),
    "unicos": backnote_auth.x.nunique(dropna=False).sum()
})
duplicate_count = backnote_auth.x.duplicated().sum()
print(f"Duplicados: {duplicate_count}")
audit.head(100)

Audit of the data as it comes from repo: https://archive.ics.uci.edu/dataset/267/banknote+authentication
  - Feature columns: ['variance', 'skewness', 'curtosis', 'entropy']
  - Target columns: ['class']
  - Feature:  (1372, 4)
  - Target:  (1372, 1)
Duplicados: 24

             tipo  ausentes  porcentaje_ausentes  unicos
variance  float64         0                  0.0    5020
skewness  float64         0                  0.0    5020
curtosis  float64         0                  0.0    5020
entropy   float64         0                  0.0    5020

In [104]:
#dropping duplicates
combined_df = pd.concat([backnote_auth.x, backnote_auth.y], axis=1)
clean_combined = combined_df.drop_duplicates()

x = clean_combined.drop(columns=["class"])
y = clean_combined["class"].to_frame()

print("")

feature_columns = list(x.columns)
target_columns = list(y.columns)
print("Audit after removing duplicates")
print(f"  - Feature columns: {feature_columns}")
print(f"  - Target columns: {target_columns}")
print("  - Feature: ", x.shape)
print("  - Target: ", y.shape)
duplicate_count = x.duplicated().sum()
print(f"  - Target dentro de X: {list(y.columns)[0] in x.columns}")
print(f"  - Duplicados: {duplicate_count}")
audit.head(100)

Audit after removing duplicates
  - Feature columns: ['variance', 'skewness', 'curtosis', 'entropy']
  - Target columns: ['class']
  - Feature:  (1348, 4)
  - Target:  (1348, 1)
  - Target dentro de X: False
  - Duplicados: 0

             tipo  ausentes  porcentaje_ausentes  unicos
variance  float64         0                  0.0    5020
skewness  float64         0                  0.0    5020
curtosis  float64         0                  0.0    5020
entropy   float64         0                  0.0    5020

False